variables:
  build.increment: $[counter('buildnumber', 10000)]
  build.version: 1.5.0-ci-$(build.increment)
  build.configuration: Release
  build.arguments: /t:Build /p:Configuration=$(build.configuration) /p:BuildVersion=$(build.version) /p:Branch=$(Build.SourceBranch)

trigger:
  - master
  - refs/tags/*

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  
  steps:
  - task: msbuild@1
    displayName: Build and Package
    inputs: 
      solution: Eto.Parse.sln
      msbuildArguments: $(build.arguments)
  - task: PublishBuildArtifacts@1
    displayName: Publish nupkg
    inputs:
      pathtoPublish: artifacts/nuget/$(build.configuration)
      artifactName: nuget
      publishLocation: container
  - task: PublishBuildArtifacts@1
    displayName: Publish tests
    inputs:
      pathtoPublish: artifacts/test/$(build.configuration)
      artifactName: test
      publishLocation: container
